DELETE FROM PUBLIC.CURRENCY;
INSERT INTO PUBLIC.CURRENCY (ID, NAME, SHORT, ISO) VALUES ('руб', 'рубль', 'р', 'rur');
INSERT INTO PUBLIC.CURRENCY (ID, NAME, SHORT, ISO) VALUES ('usd', 'usd', '$', 'usd');
INSERT INTO PUBLIC.CURRENCY (ID, NAME, SHORT, ISO) VALUES ('eur', 'euro', '€', 'eur');
