DROP SEQUENCE IF EXISTS GROUP_SEQ;
CREATE SEQUENCE GROUP_SEQ;

DROP TABLE IF EXISTS FACTS;
CREATE TABLE FACTS(
  FACT_ID INT DEFAULT GROUP_SEQ.nextval PRIMARY KEY NOT NULL,
  USER_ID INT NOT NULL,
  DATE DATE NOT NULL,
  AMOUNT NUMBER(18,2) NOT NULL,
  ACCOUNT_ID INT DEFAULT 0,
  CATEGORY_ID INT DEFAULT 0,
  DESCRIPTION VARCHAR(100) DEFAULT '',
  CONSTRAINT FACTS_USERS_USER_ID_fk FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (USER_ID)
);

DROP TABLE IF EXISTS ACCOUNTS;
CREATE TABLE ACCOUNTS(
  ACCOUNT_ID INT DEFAULT GROUP_SEQ.nextval PRIMARY KEY NOT NULL,
  USER_ID INT NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  CURRENCY VARCHAR(5) NOT NULL ,
  AMOUNT NUMBER(18,2) NOT NULL ,
  CONSTRAINT ACCOUNTS_USERS_USER_ID_fk FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (USER_ID)
);

DROP TABLE IF EXISTS CATEGORIES;
CREATE TABLE CATEGORIES(
  CATEGORY_ID INT  DEFAULT GROUP_SEQ.nextval PRIMARY KEY NOT NULL,
  UCATEGORY_IDSER_ID INT NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  CONSTRAINT CATEGORIES_USERS_USER_ID_fk FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (USER_ID)
);

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS
(
  USER_ID INTEGER DEFAULT GROUP_SEQ.nextval PRIMARY KEY NOT NULL,
  LOGIN VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL
);
CREATE UNIQUE INDEX "users_login_uindex" ON USERS (LOGIN);
